import Link from "next/link";
import "./globals.css";
import type { Metadata } from "next";
import Header from "./Header";
import Footer from "./Footer";

export const metadata: Metadata = {
  title: "Next.js13 Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <head />
      <body className="container mx-auto bg-slate-700 text-slate-50">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
